#!/usr/bin/env python3
"""Write the project's index.html: every mv.json scene as a sub-composition on one track + the song.

Usage: python3 assemble.py <project_dir> [--snap]
Scenes must tile 0 → song end with no gaps or overlaps; each compositions/scenes/<id>.html must exist.
--snap first rounds every scene start/end in mv.json to a whole frame (1/30 s, moves cuts by ≤ 17 ms) —
needed by render.py's chunked mode; rebuild the scenes afterwards (tools/build.py).
"""
import json
import os
import sys

P = os.path.abspath(sys.argv[1])
cfg = json.load(open(os.path.join(P, "mv.json"), encoding="utf-8"))
if "--snap" in sys.argv:
    for sc in cfg["scenes"]:
        sc["start"], sc["end"] = round(round(float(sc["start"]) * 30) / 30, 4), round(round(float(sc["end"]) * 30) / 30, 4)
    json.dump(cfg, open(os.path.join(P, "mv.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print("snapped scene cuts to whole frames — rebuild the scenes: tools/build.py", P)
    sys.exit()
song = json.load(open(os.path.join(P, cfg["audiomap"]), encoding="utf-8"))["audio"]["duration_sec"]
out_dir = cfg.get("out_dir", "compositions/scenes")
prev, clips = 0.0, []
for s in cfg["scenes"]:
    a, b = float(s["start"]), float(s["end"])
    if abs(a - prev) > 1e-6:
        raise SystemExit(f"gap/overlap before {s['id']}: previous scene ends {prev}, this starts {a}")
    if not os.path.exists(os.path.join(P, out_dir, f"{s['id']}.html")):
        raise SystemExit(f"not built: {out_dir}/{s['id']}.html")
    prev = b
    clips.append(f'      <div id="el-{s["id"]}" class="frame" data-composition-id="{s["id"]}" data-composition-src="{out_dir}/{s["id"]}.html"\n'
                 f'        data-start="{a:g}" data-duration="{round(b - a, 3):g}" data-track-index="1"></div>')
end = prev
import re  # noqa: E402
seen = {}
for s in cfg["scenes"]:
    m = re.search(r'id="([^"]+)-root" data-composition-id', open(os.path.join(P, out_dir, f"{s['id']}.html"), encoding="utf-8").read())
    if m and m.group(1) in seen:
        raise SystemExit(f"scenes {seen[m.group(1)]} and {s['id']} share the id prefix {m.group(1)!r} — give one an explicit Scene(…, p=…)")
    if m:
        seen[m.group(1)] = s["id"]
if abs(end - song) > 0.05:
    print(f"warning: scenes end at {end}, song is {song}")
html = f"""<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js" integrity="sha384-sG0Hv1tP1lZCk9KQmrIbY/XNwi+OY84GQqhMscbnsoBFqAz8KNCil1kvfL3Hbbk2" crossorigin="anonymous"></script>
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ width: 1920px; height: 1080px; overflow: hidden; background: #000; }}
      #root {{ position: relative; width: 1920px; height: 1080px; overflow: hidden; }}
      .frame {{ position: absolute; inset: 0; width: 100%; height: 100%; }}
    </style>
  </head>
  <body>
    <!-- {cfg.get("title", "")} — generated by handdrawn-lyric-mv tools/assemble.py from mv.json -->
    <div id="root" data-composition-id="main" data-start="0" data-duration="{end:g}" data-width="1920" data-height="1080">
{chr(10).join(clips)}
      <audio id="el-bgm" src="{cfg["audio"]}" data-start="0" data-duration="{end:g}" data-track-index="11" data-volume="{cfg.get("volume", 0.9)}"></audio>
    </div>
    <script>
      window.__timelines = window.__timelines || {{}};
      window.__timelines["main"] = gsap.timeline({{ paused: true }});
    </script>
  </body>
</html>
"""
open(os.path.join(P, "index.html"), "w", encoding="utf-8").write(html)
print(f"wrote index.html — {len(clips)} scenes, {end:g} s")
